### ISSUE TITLE
Solc Version Issue for non-ethereum chains

### ISSUE THREAD

**Issue by ghost** [icon-project/xcall-scaffolding#1]
## Description and context

Trying to deploy solidity contracts with given compiler version returns the following error:
`Returned error: invalid opcode: opcode 0x5f not defined`

## Steps to reproduce

1. Compile solidity contracts using given truffle.config.js [solc version 0.8.20 ]
2.  Try to deploy contract to EVM chains, other then Ethereum. I tried in BSC for example

## Experienced behavior

Deploying contract fails with this error:
` Returned error: invalid opcode: opcode 0x5f not defined`

## Expected behavior

The contract should be deployed.

## Solution recommendation

This can be fixed by downgrading solc version to 0.8.19.
version: "0.8.19"
This issue arised due to:

This is because solidity 0.8.20 introduces the PUSH0(0x5f) opcode which is only supported on ETH mainnet and not on any other chains. That's why other chains can't find the PUSH0(0x5f) opcode and throw this error.
 
Referenced from: [here](https://ethereum.stackexchange.com/questions/150281/invalid-opcode-opcode-0x5f-not-defined/150286#150286)

**Comment by CyrusVorwald** [comment]
Thank you for providing this detailed information.

**Comment by FidelVe** [comment]
thank you for the report and fix, will implement it in the next update.
